[tox]
requires =
    tox
env_list =
    lint,type,py{310,311}

[testenv]
description = run tests
deps =
    pytest
commands =
    pytest {posargs:tests}

[testenv:lint]
description = format and lint
skip_install = true
deps =
    ruff
commands =
    ruff format .
    ruff check --fix .

[testenv:type]
description = run type check
skip_install = true
deps =
    mypy
commands =
    mypy {{cookiecutter.project_slug}} tests

[testenv:py310]
basepython = python3.10

[testenv:py311]
basepython = python3.11
description = Run tests and code coverage
passenv = *
deps =
    codecov
    mypy
    pytest
    pytest-cov
commands =
    pytest --cov=./ --cov-append --cov-report=xml
    codecov -e TOXENV

[testenv:py312]
description = Run linter, type check and code coverage
passenv = *
commands =
    ruff format .
    ruff check --fix .
    mypy {{cookiecutter.project_slug}} tests
    pytest --cov=./ --cov-append --cov-report=xml

[gh-actions]
python =
    3.10: py310
    3.11: py311
